name : Deploy Serverless Infrastructure 

on :
  push :  
    branches :
      - main
  pull_request:
    branches :
      - main
  
#Permissions for OpenID Connect (OIDC)

permissions:
  id-token: write
  contents: read

jobs:
  terraform :
    name : "Terraform Plan & Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
    
    steps :
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Debug Exact Repo String
      run: echo "THE EXACT STRING AWS EXPECTS IS ---> repo:${{ github.repository }}:*"

    - name: Configure AWS Credentials
      uses : aws-actions/configure-aws-credentials@v4
      with :
        role-to-assume : ${{ secrets.AWS_ROLE_ARN }}
        aws-region : ap-south-1
      
    - name : Setup Terraform
      uses : hashicorp/setup-terraform@v3

    - name : Terraform Init
      run : terraform init

    - name : Terraform Format Check
      run : terraform fmt -check
    
    - name : Terraform Plan 
      run : terraform plan -no-color

    - name : Terraform Apply
      if : github.event.name == 'push' && github.ref == 'refs/heads/main'
      run : terraform apply -auto-approve -no-color 